---
title: "2019 ARU/Remote Broadcast deployment calendar"
author: Adam Smith, USFWS Southeast Inventory and Monitoring (adam_d_smith@fws.gov)
date: "`r format(Sys.time(), '%d %B, %Y')`"
fontsize: 12
output: pdf_document
geometry: margin=0.75in
header-includes:
  - \usepackage{caption}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r calendar}
pacman::p_load(nrsmisc, dplyr, knitr, kableExtra)

start <- as.Date("2019-04-16")
end <- as.Date("2019-07-01")

# Approximate coordinates for relevant refuges
fed_coords <- data.frame(refuge = c("ALL", "CDR", "SWQ"),
                         lon = c(-75.8717, -76.3392, -76.3148),
                         lat = c(35.7678, 34.9473, 35.3821),
                         stringsAsFactors = FALSE)
rise_set <- lapply(1:nrow(fed_coords), function(i) {
  cal <- get_sun(fed_coords[i, "lon"], fed_coords[i, "lat"], start, end,
                 direction = c("sunrise", "sunset"), out_tz = "America/New_York")
  cal$refuge <- fed_coords[i, "refuge"]
  cal
})

rise_set <- do.call("rbind", rise_set) %>%
  mutate(date = factor(as.Date(sunrise), ordered = TRUE,
                       labels = format(unique(as.Date(sunrise)), format = "%d %b")),
         rise = format(sunrise + as.difftime(30, units = "mins"), format = "%H:%M"),
         set = format(sunset - as.difftime(30, units = "mins"), format = "%H:%M"),
         riset = paste(rise, set, sep = "/")) %>%
  select(Date = date, refuge, riset) %>%
  tidyr::spread(refuge, riset)
tab <- knitr::kable(rise_set, booktabs = TRUE, longtab = TRUE, linesep = "", 
  caption = "ARU sunrise/sunset deployment times by refuge for 2019. Deployment times have already been adjusted by 30 minutes relative to sunrise and sunset according to the protocol.")
kable_styling(tab, full_width = FALSE, latex_options = "striped") %>%
  row_spec(0, align = "c")
```
