---
title: "Data storage of audio files from SongMeter 2+ (ARU)"
author: Adam Smith, USFWS Southeast Inventory and Monitoring (adam_d_smith@fws.gov)
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
geometry: margin=0.75in
urlcolor: blue
graphics: yes
header-includes:
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancypagestyle{plain}
  - \fancyhf{}
  - \renewcommand{\headrulewidth}{0pt}
  - \renewcommand{\footrulewidth}{0pt}
---

\fontsize{12}{14}
\selectfont

After an ARU/remote broadcast sampling event, transfer raw recordings from the SD cards to duplicate 2+ TB external hard drives for backup and analysis.

The recordings generated by a SongMeter SM2+ include the start time of the recording using the naming convention `PREFIX_C_YYYYMMDD_hhmmss.wav`, where `PREFIX` is the programmed location prefix, and `C` is the channel (0 - left; 1 - right) for stereo recordings. If using the [Black Rail SongMeter 2+ (ARU) programming SOP](https://drive.google.com/open?id=1LFW3eHGa8eNBBsS4xyqox6vrlnHqznlE), the location prefix follows a \<ARU ID\>-\<established point ID\> naming convention. Additionally, the SongMeter will record continuously but create two recordings, one per channel, every 2 hours.

For example, consider the first two audio files generated during an ARU survey at point `CDR4H` with SongMeter `IM06`, with the recording session beginning at 10:00 PM (22:00:00) on 15 April 2019. The programmed location prefix would be `IM06-CDR4H`. The first 2 hour long files would thus have names similar to `IM06-CDR4H_0_20190415_220000.wav` for the left channel and `IM06-CDR4H_1_20190415_220000.wav` for the right channel. Subsequent files would be named similarly but with different time stamps.

## Raw recording transfer, organization, and storage

1. Access the raw audio (`.wav`) recordings on the SD card(s) in the SongMeter. The SongMeter creates files under a directory called `Data`. 

1. Select the approximately 60 - 96 `.wav` files in the `Data` directory and move them to the `YYYY_ARU_files` directory on both external hard drives, where `YYYY` is the current year.
    a. A single 2 hour recording using the [Black Rail SongMeter 2+ (ARU) programming SOP](https://drive.google.com/open?id=1LFW3eHGa8eNBBsS4xyqox6vrlnHqznlE) settings should be approximately 315 MB. Note there will be two 2-hour files for each time stamp, one for each microphone channel.

1. Record pertinent recording end date and file number information for each channel in the ARU deployment data sheet.

1. After confirming the files were copied successfully to both external hard drives, the contents of the SD card may be deleted. The SD card can now be used for another deployment.