---
title: "Data storage of image files from Bushnell Trophy Cam camera traps"
author: 
- Adam Smith, USFWS Southeast Inventory and Monitoring (adam_d_smith@fws.gov)
- David Tilson
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
geometry: margin=0.75in
urlcolor: blue
graphics: yes
header-includes:
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancypagestyle{plain}
  - \fancyhf{}
  - \renewcommand{\headrulewidth}{0pt}
  - \renewcommand{\footrulewidth}{0pt}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center")
```

\fontsize{12}{14}
\selectfont

After a camera trap sampling event based on the [Black Rail Camera Trap deployment SOP](), transfer raw images from Bushnell Trophy Cam SD card(s) to duplicate 2+ TB external hard drives for backup and analysis.

The images generated by a Bushnell Trophy Cam (model 119876C) use an unhelpful naming convention of `MMDD####.JPG`, where `####` is a sequential numbering of image photos beginning with `0001`. Other important details are stored in the Exif data associated with each image and fortunately can be extracted programmatically during post-processing.

## Raw recording transfer, organization, and storage

The vague file naming convention used by the Trophy Cam requires well-named directories for file storage. We use the convention of creating a directory matching the survey point ID, with subdirectories matching the Trophy Cam ID.

1. Create a new directory within the `YYYY_Camera_trap_files` directory on the primary external hard drive.
    a. Name this directory to match the `<survey point ID>` (e.g., `CDR22H`, `265626_CCB0021`, etc.)
    b. Within this newly-created directory, create a subdirectory named for each `<Trophy Cam ID>` that generated images (e.g., `CAM01`, `CAM02`, etc.)

1. Access the raw image (`.JPG`) files on the SD card(s) of a given Trophy Cam. 
    a. To take out the SD card, gently push in the card. A "click" indicates the card is released from the spring-loaded slot and ready to be
removed.
    b. The Trophy Cam stores images in a directory called `DCIM` and a subdirectory therein named similarly, if not identically, to `100EK113`. 

1. Copy the images to the appropriate `<Trophy Cam ID>`-named subdirectory on the primary external hard drive.
    a. Take care to place the images within the appropriate `<survey point ID>/<Trophy Cam ID>` directory.

1. Copy the `<survey point ID>`-named directory on the primary hard drive to the `YYYY_Camera_trap_files` directory on the backup external hard drive.

1. After confirming image files were copied successfully to the correct directory hierarchy on both external hard drives, the contents of the SD card may be deleted. The SD card can now be used for another deployment.
